import * as React from "react"

import { IconCheck } from "@tabler/icons-react"

import { cn } from "@/lib/utils"

function hasClassToken(className: string | undefined, token: string): boolean {
  return className?.split(/\s+/).includes(token) ?? false
}

export function MdxOrderedList({ className, ...props }: React.ComponentPropsWithoutRef<"ol">) {
  const isTaskList = hasClassToken(className, "contains-task-list")

  return (
    <ol
      {...props}
      data-slot="mdx-ordered-list"
      data-task-list={isTaskList ? "" : undefined}
      className={cn(
        "space-y-2",
        isTaskList ? "ml-0 list-none!" : "ml-6 list-outside list-decimal",
        "[&_ol]:list-[lower-alpha]",
        "[&_ol_ol]:list-[lower-roman]",
        className
      )}
    />
  )
}

export function MdxUnorderedList({ className, ...props }: React.ComponentPropsWithoutRef<"ul">) {
  const isTaskList = hasClassToken(className, "contains-task-list")

  return (
    <ul
      {...props}
      data-slot="mdx-unordered-list"
      data-task-list={isTaskList ? "" : undefined}
      className={cn(
        "space-y-2",
        isTaskList ? "ml-0 list-none!" : "ml-6 list-outside list-disc",
        "[&_ul]:list-[circle]",
        "[&_ul_ul]:list-[square]",
        className
      )}
    />
  )
}

export function MdxListItem({ className, ...props }: React.ComponentPropsWithoutRef<"li">) {
  const isTaskItem = hasClassToken(className, "task-list-item")

  return (
    <li
      {...props}
      data-slot="mdx-list-item"
      data-task-item={isTaskItem ? "" : undefined}
      className={cn(
        "leading-7",
        isTaskItem ? "relative list-none! pl-6" : "pl-1 marker:text-muted-foreground",
        "[&>p+p]:mt-3",
        "[&>ol]:mt-2",
        "[&>ul]:mt-2",
        className
      )}
    />
  )
}

export function MdxInput({
  type,
  disabled,
  checked,
  className,
  ...props
}: React.ComponentPropsWithoutRef<"input">) {
  // Only customize the disabled checkbox generated by remark-gfm.
  if (type !== "checkbox" || !disabled) {
    return (
      <input {...props} type={type} disabled={disabled} checked={checked} className={className} />
    )
  }

  return (
    <span
      data-slot="mdx-task-checkbox"
      className={cn("pointer-events-none absolute top-1.5 left-0 size-4", className)}
    >
      <input
        {...props}
        type="checkbox"
        disabled
        checked={checked}
        className="absolute inset-0 z-10 m-0 size-full opacity-0"
      />

      <span
        aria-hidden="true"
        data-checked={checked ? "" : undefined}
        className={cn(
          "flex size-4 items-center justify-center",
          "rounded-sm border shadow-xs",
          checked
            ? "border-primary bg-primary text-primary-foreground"
            : "border-input dark:bg-input/30"
        )}
      >
        {checked && <IconCheck className="size-3.5" />}
      </span>
    </span>
  )
}
