import { Box, Em, Kbd, Table } from '@chakra-ui/react'
import { MDXContent } from '@content-collections/mdx/react'
import type { MDXComponents } from 'mdx/types'

import GfmAlert from '@/components/mdx/gfm-alert'
import { H1, H2, H3, H4 } from '@/components/mdx/heading'
import { Li, Ol, Ul } from '@/components/mdx/list'
import MdxImage from '@/components/mdx/mdx-image'
import MdxLink from '@/components/mdx/mdx-link'
import CodeHighlightBlock from '@/components/mdx/shiki-highlight'
import { Code, P, Strong } from '@/components/mdx/text'
import TimelineNews from '@/components/timeline'
import { Blockquote } from '@/components/ui/blockquote'

const components: MDXComponents = {
  a: MdxLink,
  blockquote: Blockquote,
  h1: H1,
  h2: H2,
  h3: H3,
  h4: H4,
  // Tags <h5> & <h6> are not allowed in MDX content by default.
  strong: Strong,
  em: Em,
  p: P,
  ol: Ol,
  ul: Ul,
  li: Li,
  table(props) {
    return <Table.Root interactive {...props} />
  },
  thead: Table.Header,
  tfoot: Table.Footer,
  tbody: Table.Body,
  tr: Table.Row,
  td: Table.Cell,
  th: Table.ColumnHeader,
  img: MdxImage,
  pre: CodeHighlightBlock,
  code: Code,
  Kbd,
  // This tag <GithubMarkdownAlert> is generated by Rehype-Github-Alerts plugins.
  GithubMarkdownAlert: GfmAlert,
  TimelineNews,
}

export default function MdxProse({ code }: { code: string }) {
  return (
    <Box
      w="full"
      css={{
        '& > :first-child': {
          mt: '0',
        },
      }}
    >
      <MDXContent code={code} components={components} />
    </Box>
  )
}
